### PR TITLE
Update to NXP version 03.03.00

### PR DESCRIPTION
**Pull request by RobertKrikke**
Cherry-picked and fixed conflicts

### CODE REVIEW

**Comment by ldts** [comment]
@RobertKrikke didnt notice your PR till now. did you test it?
I had to do some integration changes - including an op-tee change hence why I am asking?

**Comment by RobertKrikke** [comment]
I'm not sure what you mean with "an optee change", but we tested my code with optee 3.14 in combination with a se050 and se051 and everything works fine. We tried to use your 0.0.4 version (which should be the same as my PR) and we still get problems building the code for se051 because of a missing header link (the same problem is fixed in this merge request). After we added the link again we discovered we need probably optee 3.15, because of other compile issues (not sure).

**Comment by RobertKrikke** [comment]
Compile fails because of: https://github.com/OP-TEE/optee_os/pull/4935, but still we are missing a link to an header file when building for se051. I also compared my merge request with version 0.0.4 and they are almost equal (some defines are different). I wait until we can build 0.0.4 again with an optee version and then I try to compile everything for se051 again.

**Comment by ldts** [comment]
hi @RobertKrikke do you perhaps use irc or slack so we can discuss? 
I'd like to understand how you test a bit better because ECC could not have worked as it was missing this change below after the 3.03 P&T update:
https://github.com/foundriesio/plug-and-trust/releases/tag/v0.0.3 
Took me a bit to figure it out since the build would pass but the test cases would fail.
Still I am sure your test cases are more extensive than mine hence why I ask - mine are mostly targeting our particular needs for RSA and ECC.

**Comment by RobertKrikke** [comment]
Now I understand, we are not using RSA and ECC and we are only storing some data as blob. In the near future we want the use first RSA and later also ECC. So that's the reason we did not encounter these problems. As already mentioned we wait until we can use 0.0.4 and then I create a separate pull request for the compile problem when configured to use SE051 (still a problem in 0.0.4).

**Comment by ldts** [comment]
@RobertKrikke  ah ok, awesome. I'll keep an eye for the PR. would you mind adding a @ldts to make sure I dont miss it. or ping me at jorge@foundries.io?

**Pull request closed without merging**
